trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageName: 'pipelines-javascript-docker'

steps:
- task: Docker@2
  displayName: Build image knk
  inputs:
    containerRegistry: 'azure container registry'
    repository: '$(imageName)'
    command: 'build'
    Dockerfile: 'app/Dockerfile'